### ISSUE TITLE
Can't Assembly CLI distribution nor package

### ISSUE THREAD

**Issue by thomakl** [psiotwo/sdlnot-rules#1]
Dear all,

I'm trying to assemble the CLI distribution with the command :
`mvn -P cli assembly:assembly`

Here's my output :
`[ERROR] Failed to execute goal on project sdlnot-rules-protege: Could not resolve dependencies for project cz.sio2:sdlnot-rules-protege:bundle:0.1: Failed to collect dependencies at aterm:aterm:jar:1.6: Failed to read artifact descriptor for aterm:aterm:jar:1.6: Could not transfer artifact aterm:aterm:pom:1.6 from/to krizik (http://krizik.felk.cvut.cz/m2repo): Transfer failed for http://krizik.felk.cvut.cz/m2repo/aterm/aterm/1.6/aterm-1.6.pom: Connect to krizik.felk.cvut.cz:80 [krizik.felk.cvut.cz/147.32.85.109] failed: Operation timed out (Connection timed out)`

It seems the server ([http://krizik.felk.cvut.cz/](http://krizik.felk.cvut.cz/)) where the repo are hosted is down ?

Best regards,

**Comment by psiotwo** [comment]
Fixed in [5c75f59]( https://github.com/psiotwo/sdlnot-rules/commit/5c75f590860a3c96ac968d0d1595ed6366e7b24a)
